transmission_cols = [
        "Ajuste da Rotação da Transmissão 1,0 a 1,4",
        "Ajuste da Rotação da Transmissão 1,5 a 1,9",
        "Ajuste da Rotação da Transmissão 2,0 a 2,4",
        "Ajuste da Rotação da Transmissão 2,5 a 2,9",
        ]

categories = ['Temperatura Máxima do Óleo Hidráulico Temperatura',
       'Temp. Máx. do Óleo da Transm. Temperatura do Óleo da Transmissão',
       'Ajuste da Rotação da Transmissão 0,5 a 0,9',
       'Ajuste da Rotação da Transmissão 1,0 a 1,4',
       'Ajuste da Rotação da Transmissão 2,5 a 2,9',
       'Ajuste da Rotação da Transmissão 3,0 a 3,5',
       'Ajuste da Rotação da Transmissão 1,5 a 1,9',
       'Ajuste da Rotação da Transmissão 2,0 a 2,4',
       'Combustível Consumido Consumo de combustível',
       'Taxa Média de Combustível Taxa Média de Combustível',
       'Uso do Combustível do Motor Carga Baixa',
       'Uso do Combustível do Motor Marcha Lenta',
       'Uso do Combustível do Motor Carga Alta',
       'Uso do Combustível do Motor Carga Média',
       'Uso do Combustível do Motor Chave-Ligada',
       'Distância Percorrida em Avanço e em Marcha à Ré Avanço',
       'Distância Percorrida em Avanço e em Marcha à Ré Marcha à Ré',
       'Temp. Máx. do Líq. de Arrefecimento Temperatura',
       'Tempo em Avanço e em Marcha à Ré Avanço',
       'Tempo em Avanço e em Marcha à Ré Marcha à Ré',
       'Tempo em Avanço e em Marcha à Ré Neutro',
       'Tempo em Avanço e em Marcha à Ré Estacionar',
       'Uso do Motor Carga Baixa', 'Uso do Motor Marcha Lenta',
       'Uso do Motor Carga Alta', 'Uso do Motor Carga Média',
       'Uso do Motor Chave-Ligada',
       'Nível do Tanque de Combustível Nível de Combustível']

new_columns = {
    'Temperatura Máxima do Óleo Hidráulico Temperatura': 'Temp. Máx. Óleo Hidr.',
       'Temp. Máx. do Óleo da Transm. Temperatura do Óleo da Transmissão': 'Temp. Máx. Óleo Transm.',
       'Ajuste da Rotação da Transmissão 0,5 a 0,9': 'c',
       'Ajuste da Rotação da Transmissão 1,0 a 1,4': 'd',
       'Ajuste da Rotação da Transmissão 2,5 a 2,9': 'Ajuste da Rot. da Transm. 2,5 a 2,9',
       'Ajuste da Rotação da Transmissão 3,0 a 3,5': 'Ajuste da Rot. da Transm. 3,0 a 3,5',
       'Ajuste da Rotação da Transmissão 1,5 a 1,9': 'g',
       'Ajuste da Rotação da Transmissão 2,0 a 2,4': 'h',
       'Combustível Consumido Consumo de combustível': 'Combust. Consumido',
       'Taxa Média de Combustível Taxa Média de Combustível': 'j',
       'Uso do Combustível do Motor Carga Baixa': 'k',
       'Uso do Combustível do Motor Marcha Lenta': 'l',
       'Uso do Combustível do Motor Carga Alta': 'm',
       'Uso do Combustível do Motor Carga Média': 'n',
       'Uso do Combustível do Motor Chave-Ligada': 'o',
       'Distância Percorrida em Avanço e em Marcha à Ré Avanço': 'p',
       'Distância Percorrida em Avanço e em Marcha à Ré Marcha à Ré': 'q',
       'Temp. Máx. do Líq. de Arrefecimento Temperatura': 'Temp. Máx. Líq. Arref.',
       'Tempo em Avanço e em Marcha à Ré Avanço': 'Tempo em Avanço',
       'Tempo em Avanço e em Marcha à Ré Marcha à Ré': 'Tempo em Ré',
       'Tempo em Avanço e em Marcha à Ré Neutro': 'u',
       'Tempo em Avanço e em Marcha à Ré Estacionar': 'v',
       'Uso do Motor Carga Baixa': 'w',
       'Uso do Motor Marcha Lenta': 'x',
       'Uso do Motor Carga Alta': 'Uso motor Alta',
       'Uso do Motor Carga Média': 'Uso motor Média',
       'Uso do Motor Chave-Ligada': 'aa',
       'Nível do Tanque de Combustível Nível de Combustível': 'bb'
}